/* ==========================================================================
   Chinese Learning Dataset (Tiếng Trung)
   - ZH_VOCABULARY_DATA
   - ZH_GRAMMAR_DATA
   - ZH_PHRASES_DATA
   - Category Maps (ZH_VOCAB_CATEGORIES, ZH_GRAMMAR_CATEGORIES, ZH_PHRASE_CATEGORIES)
   ========================================================================== */

const ZH_VOCABULARY_DATA = {
  greeting: [
    {
      word: "你好",
      phonetic: "nǐ hǎo",
      meaning: "Xin chào",
      example: "你好！很高兴认识你。",
      exampleVi: "Xin chào! Rất vui được quen biết bạn.",
    },
    {
      word: "早上好",
      phonetic: "zǎoshang hǎo",
      meaning: "Chào buổi sáng",
      example: "大家早上好，今天开始新的工作。",
      exampleVi: "Chào buổi sáng mọi người, hôm nay bắt đầu công việc mới.",
    },
    {
      word: "谢谢",
      phonetic: "xièxie",
      meaning: "Cảm ơn",
      example: "谢谢你的热情帮助！",
      exampleVi: "Cảm ơn sự giúp đỡ nhiệt tình của bạn!",
    },
    {
      word: "不客气",
      phonetic: "bú kèqì",
      meaning: "Không có chi, đừng khách sáo",
      example: "不用谢，不客气！",
      exampleVi: "Không cần cảm ơn, đừng khách sáo!",
    },
    {
      word: "对不起",
      phonetic: "duìbuqǐ",
      meaning: "Xin lỗi",
      example: "对不起，我来晚了。",
      exampleVi: "Xin lỗi, tôi đến muộn rồi.",
    },
    {
      word: "没关系",
      phonetic: "méi guānxi",
      meaning: "Không sao đâu, không hề gì",
      example: "没关系，下次注意就好。",
      exampleVi: "Không sao, lần sau chú ý là được rồi.",
    },
    {
      word: "再见",
      phonetic: "zàijiàn",
      meaning: "Tạm biệt, hẹn gặp lại",
      example: "明天见，祝你周末愉快，再见！",
      exampleVi: "Hẹn ngày mai gặp, chúc bạn cuối tuần vui vẻ, tạm biệt!",
    },
    {
      word: "请问",
      phonetic: "qǐngwèn",
      meaning: "Xin hỏi, làm phiền cho hỏi",
      example: "请问，去会议室怎么走？",
      exampleVi: "Xin hỏi, đi đến phòng họp đi đường nào?",
    },
    {
      word: "麻烦你",
      phonetic: "máfan nǐ",
      meaning: "Làm phiền bạn, phiền bạn",
      example: "麻烦你帮我复印一下这份资料。",
      exampleVi: "Phiền bạn photo giúp tôi tài liệu này một chút.",
    },
    {
      word: "方便",
      phonetic: "fāngbiàn",
      meaning: "Tiện lợi, thuận tiện",
      example: "您现在说话方便吗？",
      exampleVi: "Bây giờ ngài có tiện nói chuyện không?",
    },
  ],
  office: [
    {
      word: "会议",
      phonetic: "huìyì",
      meaning: "Cuộc họp, hội nghị",
      example: "下午两点我们有一个部门会议。",
      exampleVi: "2 giờ chiều chúng ta có một cuộc họp phòng ban.",
    },
    {
      word: "邮件",
      phonetic: "yóujiàn",
      meaning: "Thư điện tử, email",
      example: "请查收我刚才发的邮件。",
      exampleVi: "Vui lòng kiểm tra email tôi vừa gửi.",
    },
    {
      word: "报告",
      phonetic: "bàogào",
      meaning: "Báo cáo",
      example: "周五之前必须提交月度报告。",
      exampleVi: "Trước thứ Sáu bắt buộc phải nộp báo cáo tháng.",
    },
    {
      word: "客户",
      phonetic: "kèhù",
      meaning: "Khách hàng",
      example: "我们要为客户提供最优质的服务。",
      exampleVi: "Chúng ta cần cung cấp dịch vụ tốt nhất cho khách hàng.",
    },
    {
      word: "项目",
      phonetic: "xiàngmù",
      meaning: "Dự án",
      example: "这个新项目由技术部负责。",
      exampleVi: "Dự án mới này do bộ phận kỹ thuật phụ trách.",
    },
    {
      word: "领导",
      phonetic: "lǐngdǎo",
      meaning: "Lãnh đạo, sếp",
      example: "这份方案需要领导签字批准。",
      exampleVi: "Phương án này cần sếp ký tên phê duyệt.",
    },
    {
      word: "加班",
      phonetic: "jiābān",
      meaning: "Tăng ca, làm thêm giờ",
      example: "为了赶进度，今晚大家需要加班。",
      exampleVi: "Để kịp tiến độ, tối nay mọi người cần tăng ca.",
    },
    {
      word: "合同",
      phonetic: "hétong",
      meaning: "Hợp đồng",
      example: "双方已经正式签署了合作合同。",
      exampleVi: "Hai bên đã chính thức ký kết hợp đồng hợp tác.",
    },
    {
      word: "合作",
      phonetic: "hézuò",
      meaning: "Hợp tác",
      example: "非常期待与贵公司的愉快合作。",
      exampleVi: "Rất mong chờ sự hợp tác vui vẻ với quý công ty.",
    },
    {
      word: "方案",
      phonetic: "fāng'àn",
      meaning: "Phương án, kế hoạch",
      example: "请大家提出优化方案的建议。",
      exampleVi: "Xin mọi người đưa ra đề xuất tối ưu phương án.",
    },
    {
      word: "进度",
      phonetic: "jìndù",
      meaning: "Tiến độ",
      example: "目前开发进度非常顺利。",
      exampleVi: "Hiện tại tiến độ phát triển rất thuận lợi.",
    },
    {
      word: "安排",
      phonetic: "ānpái",
      meaning: "Sắp xếp, bố trí",
      example: "经理已经安排好下周的出差行程。",
      exampleVi: "Quản lý đã sắp xếp xong lịch công tác tuần tới.",
    },
    {
      word: "讨论",
      phonetic: "tǎolùn",
      meaning: "Thảo luận",
      example: "我们明天再深入讨论这个问题。",
      exampleVi: "Ngày mai chúng ta sẽ thảo luận sâu hơn về vấn đề này.",
    },
    {
      word: "负责",
      phonetic: "fùzé",
      meaning: "Phụ trách, chịu trách nhiệm",
      example: "王经理负责这次活动的统筹。",
      exampleVi: "Quản lý Vương phụ trách điều phối hoạt động lần này.",
    },
  ],
  dining: [
    {
      word: "菜单",
      phonetic: "càidān",
      meaning: "Thực đơn, menu",
      example: "服务员，请给我们拿一份菜单。",
      exampleVi: "Phục vụ ơi, vui lòng lấy cho chúng tôi một cuốn thực đơn.",
    },
    {
      word: "点菜",
      phonetic: "diǎncài",
      meaning: "Gọi món, đặt món",
      example: "你们准备好点菜了吗？",
      exampleVi: "Các bạn đã sẵn sàng gọi món chưa?",
    },
    {
      word: "买单",
      phonetic: "mǎidān",
      meaning: "Tính tiền, thanh toán",
      example: "服务员，买单，可以刷卡吗？",
      exampleVi: "Phục vụ ơi tính tiền, có thể quẹt thẻ không?",
    },
    {
      word: "服务员",
      phonetic: "fúwùyuán",
      meaning: "Nhân viên phục vụ",
      example: "服务员，请加一点水。",
      exampleVi: "Phục vụ ơi, xin thêm chút nước.",
    },
    {
      word: "好吃",
      phonetic: "hǎochī",
      meaning: "Ngon miệng",
      example: "这里的北京烤鸭真好吃！",
      exampleVi: "Vịt quay Bắc Kinh ở đây ngon thật đấy!",
    },
    {
      word: "辣",
      phonetic: "là",
      meaning: "Cay",
      example: "这道菜有点辣，你能吃辣吗？",
      exampleVi: "Món này hơi cay, bạn ăn cay được không?",
    },
    {
      word: "推荐",
      phonetic: "tuījiàn",
      meaning: "Giới thiệu, đề xuất, gợi ý",
      example: "请问你们店里有什么招牌菜推荐？",
      exampleVi: "Xin hỏi quán mình có món đặc trưng nào gợi ý không?",
    },
    {
      word: "打包",
      phonetic: "dǎbāo",
      meaning: "Gói mang về",
      example: "吃不完的菜请帮我们打包。",
      exampleVi: "Những món ăn chưa hết xin gói mang về giúp chúng tôi.",
    },
    {
      word: "发票",
      phonetic: "fāpiào",
      meaning: "Hóa đơn đỏ, hóa đơn VAT",
      example: "结账后请给我开一张发票。",
      exampleVi: "Sau khi thanh toán vui lòng xuất hóa đơn giúp tôi.",
    },
    {
      word: "忌口",
      phonetic: "jìkǒu",
      meaning: "Kiêng ăn, dị ứng thức ăn",
      example: "请问各位有什么忌口的食物吗？",
      exampleVi: "Xin hỏi mọi người có kiêng món ăn nào không?",
    },
  ],
  shopping: [
    {
      word: "多少钱",
      phonetic: "duōshao qián",
      meaning: "Bao nhiêu tiền",
      example: "请问这件衣服多少钱？",
      exampleVi: "Xin hỏi bộ quần áo này bao nhiêu tiền?",
    },
    {
      word: "便宜",
      phonetic: "piányi",
      meaning: "Rẻ, giá rẻ",
      example: "太贵了，能不能便宜一点？",
      exampleVi: "Đắt quá, có thể bớt rẻ hơn một chút không?",
    },
    {
      word: "打折",
      phonetic: "dǎzhé",
      meaning: "Giảm giá, chiết khấu",
      example: "今天全场商品打八折。",
      exampleVi: "Hôm nay toàn bộ sản phẩm giảm giá 20%.",
    },
    {
      word: "试穿",
      phonetic: "shìchuān",
      meaning: "Mặc thử, ướm thử",
      example: "请问试衣间在哪？我想试穿一下。",
      exampleVi: "Xin hỏi phòng thử đồ ở đâu? Tôi muốn mặc thử.",
    },
    {
      word: "质量",
      phonetic: "zhìliàng",
      meaning: "Chất lượng",
      example: "这款鞋子的质量非常好。",
      exampleVi: "Chất lượng của đôi giày này rất tốt.",
    },
    {
      word: "扫码支付",
      phonetic: "sǎomǎ zhīfù",
      meaning: "Quét mã thanh toán",
      example: "支持微信和支付宝扫码支付。",
      exampleVi: "Hỗ trợ quét mã thanh toán qua WeChat và Alipay.",
    },
    {
      word: "现金",
      phonetic: "xiànjīn",
      meaning: "Tiền mặt",
      example: "请问可以收现金吗？",
      exampleVi: "Xin hỏi có nhận tiền mặt không?",
    },
    {
      word: "优惠",
      phonetic: "yōuhuì",
      meaning: "Ưu đãi",
      example: "会员购买有专属优惠。",
      exampleVi: "Hội viên mua hàng có ưu đãi riêng.",
    },
  ],
  travel: [
    {
      word: "机场",
      phonetic: "jīchǎng",
      meaning: "Sân bay",
      example: "我明天早上要送客户去机场。",
      exampleVi: "Sáng mai tôi phải tiễn khách ra sân bay.",
    },
    {
      word: "地铁",
      phonetic: "dìtiě",
      meaning: "Tàu điện ngầm",
      example: "坐地铁去市中心非常方便快捷。",
      exampleVi: "Đi tàu điện ngầm đến trung tâm thành phố rất tiện lợi và nhanh chóng.",
    },
    {
      word: "出租车",
      phonetic: "chūzūchē",
      meaning: "Xe taxi",
      example: "门口有很多出租车在排队等候。",
      exampleVi: "Ở cổng có rất nhiều xe taxi đang xếp hàng đợi.",
    },
    {
      word: "酒店",
      phonetic: "jiǔdiàn",
      meaning: "Khách sạn",
      example: "我们在携程上预订了这家五星级酒店。",
      exampleVi: "Chúng tôi đã đặt khách sạn 5 sao này trên mạng.",
    },
    {
      word: "护照",
      phonetic: "hùzhào",
      meaning: "Hộ chiếu",
      example: "办理登机手续时需要出示护照。",
      exampleVi: "Khi làm thủ tục lên máy bay cần xuất trình hộ chiếu.",
    },
    {
      word: "行李",
      phonetic: "xíngli",
      meaning: "Hành lý",
      example: "请看管好随身携带的行李。",
      exampleVi: "Vui lòng trông coi cẩn thận hành lý mang theo.",
    },
    {
      word: "预订",
      phonetic: "yùdìng",
      meaning: "Đặt trước, book trước",
      example: "我已经提前预订了高铁票。",
      exampleVi: "Tôi đã đặt trước vé tàu cao tốc rồi.",
    },
    {
      word: "怎么走",
      phonetic: "zěnme zǒu",
      meaning: "Đi như thế nào, đường nào",
      example: "请问去故宫博物院怎么走？",
      exampleVi: "Xin hỏi đi đến Bảo tàng Cố Cung đi đường nào?",
    },
  ],
  tech: [
    {
      word: "电脑",
      phonetic: "diànnǎo",
      meaning: "Máy tính",
      example: "我的工作电脑需要升级配置。",
      exampleVi: "Máy tính làm việc của tôi cần nâng cấp cấu hình.",
    },
    {
      word: "软件",
      phonetic: "ruǎnjiàn",
      meaning: "Phần mềm",
      example: "我们正在测试最新的办公软件。",
      exampleVi: "Chúng tôi đang kiểm thử phần mềm văn phòng mới nhất.",
    },
    {
      word: "账号",
      phonetic: "zhànghào",
      meaning: "Tài khoản",
      example: "请输入您的账号和密码登录。",
      exampleVi: "Vui lòng nhập tài khoản và mật khẩu của bạn để đăng nhập.",
    },
    {
      word: "密码",
      phonetic: "mìmǎ",
      meaning: "Mật khẩu",
      example: "为了安全，请定期更换密码。",
      exampleVi: "Vì an toàn, hãy đổi mật khẩu định kỳ.",
    },
    {
      word: "下载",
      phonetic: "xiàzǎi",
      meaning: "Tải xuống, download",
      example: "点击此链接即可下载安装包。",
      exampleVi: "Bấm vào đường link này là có thể tải gói cài đặt.",
    },
    {
      word: "数据",
      phonetic: "shùjù",
      meaning: "Dữ liệu, data",
      example: "每天下班前要记得备份数据库。",
      exampleVi: "Mỗi ngày trước khi tan làm hãy nhớ sao lưu cơ sở dữ liệu.",
    },
    {
      word: "网络",
      phonetic: "wǎngluò",
      meaning: "Mạng internet",
      example: "办公室的网络连接非常稳定。",
      exampleVi: "Kết nối mạng của văn phòng rất ổn định.",
    },
    {
      word: "修复",
      phonetic: "xiūfù",
      meaning: "Sửa chữa, fix lỗi (bug)",
      example: "开发团队已在第一时间修复了漏洞。",
      exampleVi: "Đội ngũ phát triển đã sửa lỗi ngay lập tức.",
    },
  ],
  time: [
    {
      word: "今天",
      phonetic: "jīntiān",
      meaning: "Hôm nay",
      example: "今天天气很好，阳光明媚。",
      exampleVi: "Hôm nay thời tiết rất đẹp, trời nắng chan hòa.",
    },
    {
      word: "明天",
      phonetic: "míngtiān",
      meaning: "Ngày mai",
      example: "明天上午九点准时开会。",
      exampleVi: "Sáng mai 9 giờ đúng họp.",
    },
    {
      word: "星期",
      phonetic: "xīngqī",
      meaning: "Tuần, thứ trong tuần",
      example: "这个星期五我们有团建活动。",
      exampleVi: "Thứ Sáu tuần này chúng ta có hoạt động team building.",
    },
    {
      word: "现在",
      phonetic: "xiànzài",
      meaning: "Bây giờ, hiện tại",
      example: "现在是北京时间上午十点整。",
      exampleVi: "Bây giờ là 10 giờ đúng sáng theo giờ Bắc Kinh.",
    },
    {
      word: "几点",
      phonetic: "jǐ diǎn",
      meaning: "Mấy giờ",
      example: "请问飞机几点起飞？",
      exampleVi: "Xin hỏi máy bay mấy giờ cất cánh?",
    },
    {
      word: "准时",
      phonetic: "zhǔnshí",
      meaning: "Đúng giờ",
      example: "请大家准时出席会议。",
      exampleVi: "Xin mọi người có mặt đúng giờ tham dự cuộc họp.",
    },
    {
      word: "提前",
      phonetic: "tíqián",
      meaning: "Sớm hơn, trước thời hạn",
      example: "项目已经提前三天顺利交付。",
      exampleVi: "Dự án đã được bàn giao thuận lợi trước thời hạn 3 ngày.",
    },
    {
      word: "延迟",
      phonetic: "yánchí",
      meaning: "Trì hoãn, trễ, delay",
      example: "因为天气原因，航班延迟起飞。",
      exampleVi: "Do nguyên nhân thời tiết, chuyến bay bị hoãn giờ bay.",
    },
  ],
  feelings: [
    {
      word: "开心",
      phonetic: "kāixīn",
      meaning: "Vui vẻ, hạnh phúc",
      example: "今天和朋友们聚会非常开心。",
      exampleVi: "Hôm nay tụ họp cùng bạn bè rất vui vẻ.",
    },
    {
      word: "累",
      phonetic: "lèi",
      meaning: "Mệt mỏi",
      example: "工作了一整天，觉得有点累。",
      exampleVi: "Làm việc cả ngày, cảm thấy hơi mệt mỏi.",
    },
    {
      word: "放心",
      phonetic: "fàngxīn",
      meaning: "Yên tâm, an tâm",
      example: "交给我办，请您放心！",
      exampleVi: "Giao cho tôi làm, xin ngài cứ yên tâm!",
    },
    {
      word: "满意",
      phonetic: "mǎnyì",
      meaning: "Hài lòng, vừa ý",
      example: "客户对我们的设计方案非常满意。",
      exampleVi: "Khách hàng rất hài lòng với phương án thiết kế của chúng tôi.",
    },
    {
      word: "期待",
      phonetic: "qīdài",
      meaning: "Kỳ vọng, mong chờ",
      example: "非常期待与大家再次相聚。",
      exampleVi: "Rất mong chờ được gặp lại mọi người một lần nữa.",
    },
    {
      word: "赞成",
      phonetic: "zànchéng",
      meaning: "Tán thành, đồng tình",
      example: "大家都赞成经理提出的新提议。",
      exampleVi: "Mọi người đều tán thành đề xuất mới của quản lý.",
    },
  ],
};

const ZH_GRAMMAR_DATA = {
  ba_sentence: [
    {
      title: "Câu chữ 把 (把字句)",
      formula: "Chủ ngữ + 把 + Tân ngữ + Động từ + Thành phần khác",
      usage: "Dùng để nhấn mạnh sự tác động làm thay đổi vị trí, trạng thái hoặc kết quả của tân ngữ.",
      example: "请把这份合同打印出来。",
      exampleVi: "Làm ơn in bản hợp đồng này ra giúp tôi. (Qǐng bǎ zhè fèn hétong dǎyìn chūlái)",
      note: "Động từ chính bắt buộc phải kèm thành phần khác (bổ ngữ, trợ từ 了, v.v.), không đứng đơn độc.",
    },
  ],
  bei_sentence: [
    {
      title: "Câu bị động chữ 被 (被字句)",
      formula: "Chủ ngữ + 被 (让/叫) + Tác nhân + Động từ + Thành phần khác",
      usage: "Dùng để biểu thị đối tượng chủ ngữ chịu sự tác động, biến đổi bởi một tác nhân bên ngoài.",
      example: "我的文件被同事不小心删除了。",
      exampleVi: "Tài liệu của tôi bị đồng nghiệp vô tình xóa mất rồi. (Wǒ de wénjiàn bèi tóngshì bù xiǎoxīn shānchú le)",
      note: "Trong khẩu ngữ thân mật thường dùng '让' (ràng) hoặc '叫' (jiào) thay thế cho '被'.",
    },
  ],
  bijiao_sentence: [
    {
      title: "Câu so sánh chữ 比 (比字句)",
      formula: "A + 比 + B + Tính từ / (Động từ + Bổ ngữ)",
      usage: "Dùng để so sánh mức độ khác nhau giữa hai đối tượng A và B.",
      example: "今年的业绩比去年好很多。",
      exampleVi: "Thành tích năm nay tốt hơn năm ngoái rất nhiều. (Jīnnián de yèjì bǐ qùnián hǎo hěn duō)",
      note: "Không thêm các phó từ chỉ mức độ như '很', '非常' ngay trước tính từ trong câu so sánh chữ 比.",
    },
  ],
  shide_structure: [
    {
      title: "Cấu trúc nhấn mạnh 是...的",
      formula: "Chủ ngữ + 是 + [Thời gian / Địa điểm / Phương thức] + Động từ + 的",
      usage: "Dùng để nhấn mạnh một chi tiết cụ thể (thời gian, nơi chốn, phương thức, mục đích) của hành động đã xảy ra.",
      example: "我们是坐高铁来上海的。",
      exampleVi: "Chúng tôi đến Thượng Hải bằng tàu cao tốc đấy. (Wǒmen shì zuò gāotiě lái Shànghǎi de)",
      note: "Hành động nhất định phải là sự việc đã diễn ra trong quá khứ.",
    },
  ],
  aspect_particles: [
    {
      title: "Trợ từ động thái: 了, 着, 过",
      formula: "Động từ + 了 (Hoàn thành) / 着 (Đang tiếp diễn) / 过 (Từng trải nghiệm)",
      usage: "Biểu thị trạng thái thời gian và khía cạnh diễn tiến của hành động.",
      example: "我看过这本书，现在正写着总结呢。",
      exampleVi: "Tôi từng đọc cuốn sách này rồi, hiện giờ đang viết tóm tắt đây. (Wǒ kànguo zhè běn shū, xiànzài zhèng xiězhe zǒngjié ne)",
      note: "'了' biểu thị hành động đã hoàn tất; '着' biểu thị trạng thái duy trì; '过' biểu thị đã từng trải qua.",
    },
  ],
  result_complement: [
    {
      title: "Bổ ngữ Kết quả & Khả năng",
      formula: "Động từ + Kết quả (完, 懂, 见...) / Động từ + 得/不 + Khả năng",
      usage: "Biểu thị kết quả đạt được sau hành vi hoặc khả năng có thể hoàn thành hành động hay không.",
      example: "这个任务今天能做完吗？我看不太清楚。",
      exampleVi: "Nhiệm vụ này hôm nay có làm xong được không? Tôi nhìn không được rõ lắm. (Zhè ge rènwù jīntiān néng zuò wán ma? Wǒ kàn bú tài qīngchǔ)",
      note: "Dạng phủ định của bổ ngữ khả năng là 'V + 不 + C', phủ định bổ ngữ kết quả dùng '没 + V + C'.",
    },
  ],
  serial_verb: [
    {
      title: "Câu liên động (连动句)",
      formula: "Chủ ngữ + Động từ 1 (+ Tân ngữ 1) + Động từ 2 (+ Tân ngữ 2)",
      usage: "Hai hay nhiều hành động liên tiếp cùng một chủ ngữ, biểu thị phương thức hoặc mục đích.",
      example: "我明天去北京参加一个国际会议。",
      exampleVi: "Ngày mai tôi đi Bắc Kinh tham gia một hội nghị quốc tế. (Wǒ míngtiān qù Běijīng cānjiā yí ge guójì huìyì)",
      note: "Hành động trước thường là phương tiện, cách thức để phục vụ cho hành động sau.",
    },
  ],
};

const ZH_PHRASES_DATA = {
  greeting: [
    {
      situation: "Lần đầu gặp mặt",
      phrase: "初次见面，请多关照。(Chūcì jiànmiàn, qǐng duō guānzhào.)",
      meaning: "Lần đầu gặp gỡ, xin được chỉ giáo và giúp đỡ nhiều hơn.",
    },
    {
      situation: "Hỏi thăm người lâu ngày không gặp",
      phrase: "好久不见，最近工作生活怎么样？(Hǎojiǔ bú jiàn, zuìjìn gōngzuò shēnghuó zěnmeyàng?)",
      meaning: "Lâu rồi không gặp, dạo này công việc cuộc sống thế nào?",
    },
    {
      situation: "Gặp lại đối tác",
      phrase: "很高兴再次见到您，一切顺利吧！(Hěn gāoxìng zàicì jiàndào nín, yíqiè shùnlì ba!)",
      meaning: "Rất vui được gặp lại ngài, mọi việc đều thuận lợi chứ ạ!",
    },
    {
      situation: "Tạm biệt và giữ liên lạc",
      phrase: "常联系，祝您工作顺利，下次见！(Cháng liánxì, zhù nín gōngzuò shùnlì, xià cì jiàn!)",
      meaning: "Thường xuyên liên lạc nhé, chúc ngài công tác tốt, hẹn gặp lần sau!",
    },
  ],
  work: [
    {
      situation: "Bắt đầu cuộc họp",
      phrase: "时间差不多了，我们现在开始开会吧。(Shíjiān chàbuduō le, wǒmen xiànzài kāishǐ kāihuì ba.)",
      meaning: "Thời gian vừa vặn rồi, chúng ta bắt đầu cuộc họp bây giờ nhé.",
    },
    {
      situation: "Hỏi ý kiến đóng góp",
      phrase: "大家对这个方案有什么意见或建议吗？(Dàjiā duì zhè ge fāng'àn yǒu shénme yìjiàn huò jiànyì ma?)",
      meaning: "Mọi người có ý kiến hoặc đề xuất gì cho phương án này không?",
    },
    {
      situation: "Báo cáo tiến độ",
      phrase: "本周的项目任务已经全部按时完成了。(Běn zhōu de xiàngmù rènwù yǐjīng quánbù ànshí wánchéng le.)",
      meaning: "Nhiệm vụ dự án của tuần này đều đã hoàn thành đúng hạn.",
    },
    {
      situation: "Gửi email xác nhận",
      phrase: "我已经把详细资料发到您的电子邮箱了。(Wǒ yǐjīng bǎ xiángxì zīliào fā dào nín de diànzǐ yóuxiāng le.)",
      meaning: "Tôi đã gửi tài liệu chi tiết vào hòm thư điện tử của ngài rồi.",
    },
    {
      situation: "Xin ý kiến chỉ đạo của lãnh đạo",
      phrase: "领导，请您审阅一下这份报告并给予指导。(Lǐngdǎo, qǐng nín shěnyuè yíxià zhè fèn bàogào bìng jǐyǔ zhǐdǎo.)",
      meaning: "Sếp ơi, xin sếp duyệt bản báo cáo này và cho ý kiến chỉ đạo ạ.",
    },
  ],
  dining: [
    {
      situation: "Gọi phục vụ xin thực đơn",
      phrase: "服务员，请给我们一份菜单，准备点菜。(Fúwùyuán, qǐng gěi wǒmen yí fèn càidān, zhǔnbèi diǎncài.)",
      meaning: "Phục vụ ơi, vui lòng cho xin thực đơn, chúng tôi chuẩn bị gọi món.",
    },
    {
      situation: "Hỏi món ngon đặc sản",
      phrase: "请问你们店里有什么招牌菜推荐？(Qǐngwèn nǐmen diàn lǐ yǒu shénme zhāopái cài tuījiàn?)",
      meaning: "Xin hỏi nhà hàng mình có món ăn đặc trưng nào gợi ý không?",
    },
    {
      situation: "Yêu cầu không ăn cay",
      phrase: "我们不吃辣，请做清淡少油一点。(Wǒmen bù chī là, qǐng zuò qīngdàn shǎo yóu yìdiǎn.)",
      meaning: "Chúng tôi không ăn cay, xin hãy làm thanh đạm và ít dầu một chút.",
    },
    {
      situation: "Thanh toán hoá đơn",
      phrase: "服务员买单，可以微信或者支付宝支付吗？(Fúwùyuán mǎidān, kěyǐ Wēixìn huòzhě Zhīfùbǎo zhīfù ma?)",
      meaning: "Phục vụ tính tiền giúp, có thể thanh toán qua WeChat hoặc Alipay không?",
    },
  ],
  shopping: [
    {
      situation: "Hỏi giá mặt hàng",
      phrase: "老板，请问这个多少钱一件？(Lǎobǎn, qǐngwèn zhè ge duōshao qián yí jiàn?)",
      meaning: "Chủ quán ơi, xin hỏi cái này bao nhiêu tiền một chiếc?",
    },
    {
      situation: "Thương lượng giá",
      phrase: "能便宜一点吗？如果合适我就多买几个。(Néng piányi yìdiǎn ma? Rúguǒ héshì wǒ jiù duō mǎi jǐ ge.)",
      meaning: "Có thể bớt rẻ hơn chút không? Nếu hợp lý tôi sẽ mua thêm vài cái.",
    },
    {
      situation: "Muốn thử đồ",
      phrase: "请问可以试穿一下这件外套吗？(Qǐngwèn kěyǐ shìchuān yíxià zhè jiàn wàitào ma?)",
      meaning: "Xin hỏi tôi có thể mặc thử chiếc áo khoác này được không?",
    },
    {
      situation: "Quyết định mua",
      phrase: "好的，质量挺不错的，我就要这个了。(Hǎode, zhìliàng tǐng búcuò de, wǒ jiù yào zhè ge le.)",
      meaning: "Được rồi, chất lượng rất tốt, tôi lấy cái này nhé.",
    },
  ],
  travel: [
    {
      situation: "Hỏi đường đến ga tàu điện ngầm",
      phrase: "请问最近的地铁站在哪个方向，怎么走？(Qǐngwèn zuì jìn de dìtiě zhàn zài nǎ ge fāngxiàng, zěnme zǒu?)",
      meaning: "Làm phiền cho hỏi ga tàu điện ngầm gần nhất ở hướng nào, đi thế nào ạ?",
    },
    {
      situation: "Bắt taxi đến địa điểm",
      phrase: "师傅，请带我去这个酒店，麻烦开一下后备箱。(Shīfu, qǐng dài wǒ qù zhè ge jiǔdiàn, máfan kāi yíxià hòubèixiāng.)",
      meaning: "Bác tài ơi, chở tôi đến khách sạn này với, phiền bác mở cốp xe giúp.",
    },
    {
      situation: "Check-in nhận phòng khách sạn",
      phrase: "您好，我网上预订了大床房，这是我的护照。(Nín hǎo, wǒ wǎngshang yùdìng le dàchuáng fáng, zhè shì wǒ de hùzhào.)",
      meaning: "Chào bạn, tôi đã đặt phòng giường đôi qua mạng, đây là hộ chiếu của tôi.",
    },
    {
      situation: "Hỏi phương tiện nhanh nhất",
      phrase: "去机场坐出租车需要多长时间？(Qù jīchǎng zuò chūzūchē xūyào duō cháng shíjiān?)",
      meaning: "Đi sân bay bằng taxi mất khoảng bao nhiêu thời gian?",
    },
  ],
  thanks: [
    {
      situation: "Cảm ơn chân thành",
      phrase: "非常感谢您的热情接待和大力支持！(Fēicháng gǎnxiè nín de rèqíng jiēdài hé dàlì zhīchí!)",
      meaning: "Rất cảm ơn sự đón tiếp nồng hậu và sự ủng hộ to lớn của ngài!",
    },
    {
      situation: "Nhờ vả sự giúp đỡ",
      phrase: "不好意思打扰了，您能帮我一个忙吗？(Bù hǎoyìsi dǎrǎo le, nín néng bāng wǒ yí ge máng ma?)",
      meaning: "Ngại quá làm phiền bạn rồi, bạn có thể giúp tôi một việc được không?",
    },
    {
      situation: "Xin lỗi vì sự bất tiện",
      phrase: "给您添麻烦了，真的非常抱歉！(Gěi nín tiān máfan le, zhēnde fēicháng bàoqiàn!)",
      meaning: "Đã gây thêm phiền phức cho ngài, thật sự vô cùng xin lỗi!",
    },
  ],
};

const ZH_VOCAB_CATEGORIES = {
  all: "Tất cả",
  greeting: "Chào Hỏi & Xã Giao",
  office: "Công Sở & Văn Phòng",
  dining: "Ăn Uống & Nhà Hàng",
  shopping: "Mua Sắm & Giá Cả",
  travel: "Du Lịch & Đi Lại",
  tech: "Công Nghệ & IT",
  time: "Thời Gian & Số Đếm",
  feelings: "Cảm Xúc & Đời Sống",
};

const ZH_GRAMMAR_CATEGORIES = {
  all: "Tất cả",
  ba_sentence: "Câu chữ 把",
  bei_sentence: "Câu chữ 被",
  bijiao_sentence: "Câu chữ 比",
  shide_structure: "Cấu trúc 是...的",
  aspect_particles: "Trợ từ 了/着/过",
  result_complement: "Bổ ngữ Kết quả & Khả năng",
  serial_verb: "Câu liên động",
};

const ZH_PHRASE_CATEGORIES = {
  all: "Tất cả",
  greeting: "Chào Hỏi & Xã Giao",
  work: "Công Việc & Họp Hành",
  dining: "Ăn Uống & Nhà Hàng",
  shopping: "Mua Sắm & Giá Cả",
  travel: "Hỏi Đường & Du Lịch",
  thanks: "Cảm Ơn & Giúp Đỡ",
};
